"""Fallback helpers for issuing a bed-sweep job via FTPS upload."""

from __future__ import annotations

import io
import logging
import zipfile
from typing import Any


log = logging.getLogger(__name__)


def build_bed_sweep_gcode(step_mm: float, frames: int, home_xy: bool = True) -> str:
    """Generate the G-code script used for the fallback bed sweep job."""

    stepDistance = max(0.0, float(step_mm))
    frameCount = max(1, int(frames))

    gcodeLines = [
        "; Bed sweep fallback generated by PrintMaster",
        "M400",
        "G90",
        "M17",
    ]

    if home_xy:
        gcodeLines.append("G28 X Y")

    gcodeLines.append("G91")

    for _ in range(frameCount):
        gcodeLines.append(f"G1 Z{stepDistance:.3f} F1200")
        gcodeLines.append("M400")
        gcodeLines.append("G4 P800")

    gcodeLines.append("G90")

    return "\n".join(gcodeLines) + "\n"


def upload_and_start_bed_sweep(printer: Any, gcode: str) -> None:
    """Upload the provided G-code as a 3MF and start the print."""

    uploadMethod = getattr(printer, "upload_file", None)
    startMethod = getattr(printer, "start_print", None)

    if not callable(uploadMethod) or not callable(startMethod):
        raise RuntimeError("Printer does not support upload/start for bed sweep job")

    zipBuffer = io.BytesIO()
    with zipfile.ZipFile(zipBuffer, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("bed_sweep.gcode", gcode)

    zipBuffer.seek(0)

    # Try (fileobj, filename); if not supported, fall back to a temporary file path.
    try:
        response = uploadMethod(zipBuffer, "bed_sweep.3mf")
    except TypeError:
        import os
        import tempfile

        data = zipBuffer.getvalue()
        with tempfile.NamedTemporaryFile(suffix=".3mf", delete=False) as temporaryFile:
            temporaryFile.write(data)
            temporaryPath = temporaryFile.name
        try:
            response = uploadMethod(temporaryPath)
        finally:
            try:
                os.unlink(temporaryPath)
            except Exception:
                pass
    if "226" not in str(response):
        raise RuntimeError(f"Bed sweep upload failed: {response}")

    log.info("[ref] upload_file returned success token 226")

    # Try the most specific form first, then fall back to broader signatures.
    try:
        startMethod("bed_sweep.3mf", "bed_sweep.gcode")
        return
    except TypeError:
        pass
    try:
        startMethod("bed_sweep.3mf", 1)
        return
    except TypeError:
        pass
    startMethod("bed_sweep.3mf")

